name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: ["x86_64-unknown-linux-gnu"]
    steps:
    - uses: actions/checkout@v7

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Print Rust version
      run: rustup --version

    - name: Build
      run: cargo build --target "${{ matrix.BUILD_TARGET }}" --release

    - name: Run tests
      run: cargo test --target "${{ matrix.BUILD_TARGET }}" --release
